# Generated by Django 4.2.6 on 2023-11-11 14:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_list',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='category_name', unique=True),
        ),
    ]
