# Generated by Django 4.2.6 on 2023-11-24 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_list_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('coupon_code', models.CharField(max_length=50)),
                ('discount', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('min_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        ),
    ]
