# Generated by Django 4.2.5 on 2024-02-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
