# Generated by Django 4.2.6 on 2023-10-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_account_phone_number_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
