# Generated by Django 4.2.5 on 2024-02-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
