# Generated by Django 4.2.6 on 2023-10-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Shipped', 'Shipped')], default='Pending', max_length=150),
        ),
    ]
