# Generated by Django 4.2.6 on 2023-10-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Out For Shipping', 'Out For Shipping'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
        ),
    ]
