# Generated by Django 4.2.5 on 2024-02-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Out For Shipping', 'Out For Shipping')], default='Pending', max_length=150),
        ),
    ]
