# Generated by Django 4.2.6 on 2023-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Out For Shipping', 'Out For Shipping'), ('Shipped', 'Shipped'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
