# Generated by Django 4.2.5 on 2024-02-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_salesreport_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesReport',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Out For Shipping', 'Out For Shipping'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
        ),
    ]
