# Generated by Django 4.2.5 on 2024-02-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_transaction_created_at_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150),
        ),
    ]
