# Generated by Django 4.2.5 on 2024-02-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_address_address_address_email_address_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Out For Shipping', 'Out For Shipping')], default='Pending', max_length=150),
        ),
    ]
