# Generated by Django 4.2.5 on 2024-02-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='multiple_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Out For Shipping', 'Out For Shipping'), ('Return', 'Return'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
